version: "3"

services:
  backend:
    build: ./
    ports:
      - 3001:3001
    environment:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=libraryZ
      - DB_HOST=db
      - JWT_SECRET=4io14141895198655689hggja6h8hbi46kgjgdf
    volumes:
      - ./:/app-backend
    container_name: api-libraryZ
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    restart: always